version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql_ktriel_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: devstragram
      MYSQL_USER: ktriel
      MYSQL_PASSWORD: 1234
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
